spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fitness_center?useSSL=false&serverTimezone=Europe/London
    password:
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  redis:
    host: 127.0.0.1
    port: 6379

  mail:
    host: smtp.gmail.com
    port: 587
    username: myfitnessuos@gmail.com
    password: venfhukqfgradhhz
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          starttls:
            enable: true
        auth: true
      debug: true

