spring:
  datasource:
    url: jdbc:mysql://localhost:3306/training_appointment_db?useSSL=false&serverTimezone=Europe/London
    password: 123456
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver